-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class com.android.billingclient.api.** { *; }
-keep class com.devradar.trendradar.** { *; }
-dontwarn okhttp3.**
